apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: produccion

commonLabels:
  enviroment: produccion
  version: "0.1"

bases:
  - ../../base/

patchesStrategicMerge:
  - agregar-replicas.yaml
