apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-demo-kustomize
spec:
  selector:
    matchLabels:
      app: nginx-demo-kustomize
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-demo-kustomize
    spec:
      containers:
        - name: nginx-demo-kustomize
          image: nginx:stable-alpine
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
          ports:
            - containerPort: 80
